### ISSUE TITLE
Notebooks magic cells are outdated after GA

### ISSUE THREAD

**Issue by shengnwen** [googledatalab/notebooks#104]
Some of the documentations are outdated and left behind the GA version.
For example in BigQuery magic cells page, %%bq is not used in GA version

**Comment by yebrahim** [comment]
`%%bq` is the new magic we use in post-GA pydatalab, or am I missing something? Can you point to a specific example?

**Comment by zelladoor** [comment]
`both `%bq` and %`%bq work equally well. Maybe the old %bq shouldn't? Or should come with a depreciation message?
![image](https://user-images.githubusercontent.com/1857683/27160612-cb6b86f6-5175-11e7-814f-08fc9d0e5969.png)

**Comment by yebrahim** [comment]
Ah I see, I had misunderstood.

@zelladoor is right, in Datalab, both formats are equivalent so you can use either. We don't have any deprecation plans as of now. I'll close this issue, feel free to reopen if there's still any confusion.
