### ISSUE TITLE
Beta2: Update sample notebook "Programming Language Correlation" - missing github.timeline table

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/notebooks#11]
githubarchive:github.timeline table seems to have disappeared from BQ. There are some other github tables in bigquery-public-data: github_repos that need to be checked or the sample needs to be dropped.

**Comment by parthea** [comment]
Fixed in #8 . I can pull out the specific fix in to a separate commit if required

**Comment by chmeyers** [comment]
Verified
