### ISSUE TITLE
Very hard to find this

### ISSUE THREAD

**Issue by kristianmandrup** [googledatalab/notebooks#16]
I found this via the article: https://cloudplatform.googleblog.com/2016/03/TensorFlow-machine-learning-with-financial-data-on-Google-Cloud-Platform.html

But it was very hard to find. I initially thought it would be in the https://github.com/googledatalab/datalab

Please update your Readme files or the article to make it more clear. Thanks!

**Comment by clemens-tolboom** [comment]
I agree on the hard to find but it is easy to find when one knows how.

- https://cloud.google.com/products/
- https://cloud.google.com/datalab/ has a link to this project (search for _Open Source_)

**Comment by chmeyers** [comment]
This repo is now linked from the https://github.com/googledatalab/datalab Readme.
